//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSThiSinhTrongPhongThi
    {
        public int MADK { get; set; }
        public string MAPHONGTHI { get; set; }
        public int MAKHOATHI { get; set; }
        public string SBD { get; set; }
        public string DIEMNGHE { get; set; }
        public string DIEMNOI { get; set; }
        public string DIEMVIET { get; set; }
        public string DIEMDOC { get; set; }
    
        public virtual PhongThi PhongThi { get; set; }
        public virtual ThiSinhDK ThiSinhDK { get; set; }
    }
}
