//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public int ID { get; set; }
        public string TENGV { get; set; }
        public string MAPHONGTHI { get; set; }
        public string MAKHOATHI { get; set; }
    
        public virtual PhongThi PhongThi { get; set; }
    }
}
