//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaThi
    {
        public KhoaThi()
        {
            this.PhongThis = new HashSet<PhongThi>();
        }
    
        public string MAKHOATHI { get; set; }
        public string TENKHOATHI { get; set; }
        public string TRINHDO { get; set; }
        public System.DateTime NGAYTHI { get; set; }
    
        public virtual ICollection<PhongThi> PhongThis { get; set; }
    }
}
